defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      type: posts
      path: gigs

    values:
      layout: gig
      pretitle: Gig

  -
    scope:
      type: posts
      path: blog

    values:
      layout: blost
      pretitle: Blog
      priority: 100

permalink: pretty
future: true
exclude: [vendor]
